import Footer from "./components/global/footer/Footer";
import Header from "./components/global/header/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[1600px]">
        <Header />
        <>{children}</>
        <Footer />
      </body>
    </html>
  );
}
